import React, { useState, useEffect } from 'react';
import { api } from './api';
import { useInstructorData, useClasses, useUsers } from './useQueries';
import { User, ClassSession, Enrollment, LessonSession, Availability, Blockout, StudentProgress } from './types';
import { Button } from './Button';
import { Card } from './Card';
import { Modal } from './Modal';
import { SKILLS } from './constants';
import { Calendar, CheckSquare, ChevronDown, ChevronUp, Clock, Users, ChevronLeft, ChevronRight, Plus, X, Slash } from 'lucide-react';

interface InstructorPortalProps {
  currentUser: User;
}

type Tab = 'DASHBOARD' | 'CALENDAR';

export const InstructorPortal: React.FC<InstructorPortalProps> = ({ currentUser }) => {
  const [activeTab, setActiveTab] = useState<Tab>('DASHBOARD');

  // -- DATA HOOKS --
  const { data: instructorData, isLoading: loadingInstructor, refetch: refetchInstructor } = useInstructorData(currentUser.id);
  const { data: classes = [] } = useClasses();
  const { data: allUsers = [] } = useUsers();

  const sessions = instructorData?.sessions || [];
  const availability = instructorData?.availability || [];
  const blockouts = instructorData?.blockouts || [];

  // -- DASHBOARD STATE --
  const [selectedSessionId, setSelectedSessionId] = useState<string | null>(null);
  const [expandedStudentId, setExpandedStudentId] = useState<string | null>(null);
  const [progressData, setProgressData] = useState<StudentProgress[]>([]);
  const [enrolledStudents, setEnrolledStudents] = useState<User[]>([]);

  // -- CALENDAR STATE --
  const [currentDate, setCurrentDate] = useState(new Date());

  const [isAvailModalOpen, setIsAvailModalOpen] = useState(false);
  const [isBlockoutModalOpen, setIsBlockoutModalOpen] = useState(false);

  const [availForm, setAvailForm] = useState({
    dayOfWeek: 1, // Monday default
    startTime: '09:00',
    endTime: '17:00'
  });

  const [blockoutForm, setBlockoutForm] = useState({
    date: new Date().toISOString().split('T')[0],
    startTime: '09:00',
    endTime: '17:00',
    reason: ''
  });

  // -- EFFECTS --
  useEffect(() => {
    const loadSessionDetails = async () => {
      if (selectedSessionId) {
        const session = sessions.find(s => s.id === selectedSessionId);
        if (session) {
          const students = session.enrolledUserIds
            .map(id => allUsers.find(u => u.id === id))
            .filter((u): u is User => !!u);
          setEnrolledStudents(students);

          // Fetch progress for all students
          // Note: api.getProgress returns any[] currently, we map it or use as is if types match
          const allProgressPromises = students.map(s => api.getProgress(s.id));
          const allProgressResults = await Promise.all(allProgressPromises);
          const flatProgress = allProgressResults.flat() as StudentProgress[];
          setProgressData(flatProgress);
        }
      }
    };
    loadSessionDetails();
  }, [selectedSessionId, sessions, allUsers]);

  // -- HANDLERS --
  const getClassName = (id: string) => classes.find(c => c.id === id)?.name;

  const toggleStudent = (id: string) => {
    setExpandedStudentId(expandedStudentId === id ? null : id);
  };

  const updateSkill = async (studentId: string, skillId: string, status: StudentProgress['status']) => {
    await api.updateProgress(studentId, skillId, status);
    // Optimistic update
    setProgressData(prev => {
      const existingIndex = prev.findIndex(p => p.studentId === studentId && p.skillId === skillId);
      if (existingIndex >= 0) {
        const newProg = [...prev];
        newProg[existingIndex] = { ...newProg[existingIndex], status };
        return newProg;
      }
      return [...prev, { studentId, skillId, status, lastUpdated: new Date().toISOString() }];
    });
  };

  const getSkillStatus = (studentId: string, skillId: string) => {
    return progressData.find(p => p.studentId === studentId && p.skillId === skillId)?.status || 'Not Started';
  };

  // Calendar Logic
  const getWeekDays = (date: Date) => {
    const start = new Date(date);
    start.setDate(start.getDate() - start.getDay()); // Sunday
    const days = [];
    for (let i = 0; i < 7; i++) {
      const d = new Date(start);
      d.setDate(start.getDate() + i);
      days.push(d);
    }
    return days;
  };

  const weekDays = getWeekDays(currentDate);
  const hours = Array.from({ length: 14 }, (_, i) => i + 6); // 6am to 8pm

  const handleAvailSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    try {
      await api.createAvailability({
        id: `av${Date.now()}`, // ID might be generated by backend
        instructorId: currentUser.id,
        dayOfWeek: Number(availForm.dayOfWeek),
        startTime: availForm.startTime,
        endTime: availForm.endTime
      });
      refetchInstructor();
      setIsAvailModalOpen(false);
    } catch (error: any) {
      console.error('Error saving availability:', error);
      alert('Error saving availability: ' + (error.message || JSON.stringify(error)));
    }
  };

  const handleBlockoutSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    try {
      await api.createBlockout({
        id: `blk${Date.now()}`,
        instructorId: currentUser.id,
        date: blockoutForm.date,
        startTime: blockoutForm.startTime,
        endTime: blockoutForm.endTime,
        reason: blockoutForm.reason
      });
      refetchInstructor();
      setIsBlockoutModalOpen(false);
    } catch (error: any) {
      console.error('Error saving blockout:', error);
      alert('Error saving blockout: ' + (error.message || JSON.stringify(error)));
    }
  };

  const handleDeleteAvailability = async (id: string, e: React.MouseEvent) => {
    e.stopPropagation();
    if (confirm('Remove this weekly availability slot?')) {
      await api.deleteAvailability(id);
      refetchInstructor();
    }
  };

  const handleDeleteBlockout = async (id: string, e: React.MouseEvent) => {
    e.stopPropagation();
    if (confirm('Remove this time off block?')) {
      await api.deleteBlockout(id);
      refetchInstructor();
    }
  };

  if (loadingInstructor) {
    return <div className="p-10 text-center">Loading instructor dashboard...</div>;
  }

  return (
    <div className="max-w-7xl mx-auto px-6 py-10 font-sans">
      <div className="flex flex-col md:flex-row justify-between items-start md:items-center mb-8 gap-4">
        <h1 className="text-3xl font-extrabold text-zinc-900 uppercase tracking-tight">Instructor Dashboard</h1>
        <div className="flex bg-zinc-100 p-1 rounded-lg">
          <button
            onClick={() => setActiveTab('DASHBOARD')}
            className={`px-4 py-2 text-xs font-bold uppercase tracking-wider rounded-md transition-all ${activeTab === 'DASHBOARD' ? 'bg-white text-zinc-900 shadow-sm' : 'text-zinc-500 hover:text-zinc-900'}`}
          >
            Session Roster
          </button>
          <button
            onClick={() => setActiveTab('CALENDAR')}
            className={`px-4 py-2 text-xs font-bold uppercase tracking-wider rounded-md transition-all ${activeTab === 'CALENDAR' ? 'bg-white text-zinc-900 shadow-sm' : 'text-zinc-500 hover:text-zinc-900'}`}
          >
            Availability
          </button>
        </div>
      </div>

      {activeTab === 'DASHBOARD' && (
        <div className="grid lg:grid-cols-3 gap-8 animate-in fade-in duration-300">
          {/* Left Column: Schedule List */}
          <div className="lg:col-span-1 space-y-6">
            <div className="flex justify-between items-center">
              <h2 className="text-sm font-bold text-zinc-500 uppercase tracking-widest flex items-center">
                <Calendar className="mr-2" size={16} /> Schedule
              </h2>
            </div>

            <div className="space-y-4">
              {sessions.sort((a, b) => new Date(a.startTime).getTime() - new Date(b.startTime).getTime()).map(session => (
                <Card
                  key={session.id}
                  onClick={() => setSelectedSessionId(session.id)}
                  className={`p-5 cursor-pointer border-l-4 transition-all ${selectedSessionId === session.id ? 'border-l-zinc-900 bg-zinc-50 shadow-md' : 'border-l-zinc-200 hover:border-l-zinc-400'}`}
                >
                  <div className="flex justify-between items-start mb-2">
                    <div>
                      <span className="font-bold text-zinc-900 text-lg block">{new Date(session.startTime).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}</span>
                      <span className="text-xs text-zinc-500 font-medium uppercase">{new Date(session.startTime).toLocaleDateString()}</span>
                    </div>
                    <span className="text-[10px] font-bold px-2 py-1 bg-zinc-200 rounded text-zinc-700 uppercase tracking-wide">
                      {session.enrolledUserIds.length}/{session.capacity}
                    </span>
                  </div>
                  <h3 className="font-medium text-zinc-600 text-sm mt-2">{getClassName(session.classTypeId)}</h3>
                </Card>
              ))}
              {sessions.length === 0 && <p className="text-zinc-500 italic">No classes scheduled.</p>}
            </div>

            <div className="mt-8 pt-6 border-t border-zinc-100">
              <Button variant="outline" className="w-full justify-start mb-3 border-zinc-300 text-zinc-800" onClick={() => setActiveTab('CALENDAR')}>
                Manage Availability in Calendar
              </Button>
            </div>
          </div>

          {/* Right Column: Class Roster & Skills */}
          <div className="lg:col-span-2">
            {selectedSessionId ? (
              <div className="bg-white rounded-lg shadow-sm border border-zinc-200 p-8 min-h-[600px]">
                <div className="flex justify-between items-center mb-8 border-b border-zinc-100 pb-6">
                  <div>
                    <h2 className="text-2xl font-bold text-zinc-900">{getClassName(sessions.find(s => s.id === selectedSessionId)?.classTypeId || '')}</h2>
                    <p className="text-zinc-500 flex items-center mt-2 font-medium"><Clock size={16} className="mr-2" /> {new Date(sessions.find(s => s.id === selectedSessionId)?.startTime || '').toLocaleString()}</p>
                  </div>
                  <Button size="sm" variant="outline" className="border-zinc-300 text-zinc-800">Mark All Present</Button>
                </div>

                <h3 className="font-bold text-zinc-400 text-xs uppercase tracking-widest mb-6 flex items-center">
                  <Users size={16} className="mr-2" /> Class Roster & Progress
                </h3>

                <div className="space-y-4">
                  {enrolledStudents.length === 0 ? (
                    <p className="text-zinc-500 italic">No students enrolled yet.</p>
                  ) : enrolledStudents.map(student => (
                    <div key={student.id} className="border border-zinc-200 rounded-md overflow-hidden transition-all">
                      <div
                        className="p-5 bg-zinc-50 flex justify-between items-center cursor-pointer hover:bg-zinc-100"
                        onClick={() => toggleStudent(student.id)}
                      >
                        <div className="flex items-center gap-4">
                          <img src={student.avatarUrl} alt={student.name} className="w-12 h-12 rounded-full object-cover grayscale" />
                          <div>
                            <div className="font-bold text-zinc-900 text-lg">{student.name}</div>
                            <div className="text-xs text-zinc-500 font-medium uppercase tracking-wide">Level: Beginner</div>
                          </div>
                        </div>
                        <div className="flex items-center gap-6">
                          <label className="flex items-center gap-2 text-sm text-zinc-600 cursor-pointer font-medium" onClick={(e) => e.stopPropagation()}>
                            <input type="checkbox" className="w-4 h-4 rounded text-zinc-900 focus:ring-zinc-900 border-zinc-300" />
                            Present
                          </label>
                          {expandedStudentId === student.id ? <ChevronUp size={20} className="text-zinc-400" /> : <ChevronDown size={20} className="text-zinc-400" />}
                        </div>
                      </div>

                      {expandedStudentId === student.id && (
                        <div className="p-6 bg-white border-t border-zinc-200 animate-in slide-in-from-top-2 duration-200">
                          <h4 className="text-xs font-bold text-zinc-400 uppercase tracking-widest mb-4">Skill Tracking</h4>
                          <div className="grid sm:grid-cols-2 gap-4">
                            {SKILLS.map(skill => {
                              const status = getSkillStatus(student.id, skill.id);
                              return (
                                <div key={skill.id} className="flex justify-between items-center p-3 rounded bg-zinc-50 border border-zinc-100">
                                  <span className="text-sm font-bold text-zinc-700">{skill.name}</span>
                                  <select
                                    value={status}
                                    onChange={(e) => updateSkill(student.id, skill.id, e.target.value as any)}
                                    className={`text-xs font-bold uppercase tracking-wide py-1 px-3 rounded border-0 cursor-pointer focus:ring-2 focus:ring-black
                                      ${status === 'Achieved' ? 'bg-zinc-800 text-white' :
                                        status === 'Working On' ? 'bg-zinc-200 text-zinc-800' :
                                          'bg-white border border-zinc-300 text-zinc-700'}`}
                                  >
                                    <option value="Not Started">Not Started</option>
                                    <option value="Working On">Working On</option>
                                    <option value="Achieved">Achieved</option>
                                  </select>
                                </div>
                              );
                            })}
                          </div>
                          <div className="mt-6">
                            <textarea placeholder="Add private instructor notes..." className="w-full p-4 text-sm text-zinc-900 border border-zinc-200 rounded focus:ring-2 focus:ring-zinc-900 focus:outline-none bg-zinc-50" rows={2}></textarea>
                          </div>
                        </div>
                      )}
                    </div>
                  ))}
                </div>
              </div>
            ) : (
              <div className="h-full flex flex-col items-center justify-center bg-zinc-50 border-2 border-dashed border-zinc-200 rounded-lg p-12 text-zinc-400">
                <CheckSquare size={48} className="mb-4 opacity-30" />
                <p className="text-lg font-medium">Select a class to manage roster.</p>
              </div>
            )}
          </div>
        </div>
      )}

      {activeTab === 'CALENDAR' && (
        <div className="animate-in fade-in slide-in-from-right-4 duration-300">
          <div className="flex flex-col md:flex-row items-center justify-between mb-6 gap-4">
            <div className="flex items-center gap-4">
              <div className="flex items-center bg-white border border-zinc-200 rounded-md p-1">
                <button onClick={() => setCurrentDate(new Date(currentDate.setDate(currentDate.getDate() - 7)))} className="p-1 hover:bg-zinc-100 rounded text-zinc-600"><ChevronLeft size={20} /></button>
                <span className="px-4 font-bold text-zinc-900 text-sm w-32 text-center">
                  {weekDays[0].toLocaleDateString('en-US', { month: 'short', day: 'numeric' })} - {weekDays[6].toLocaleDateString('en-US', { month: 'short', day: 'numeric' })}
                </span>
                <button onClick={() => setCurrentDate(new Date(currentDate.setDate(currentDate.getDate() + 7)))} className="p-1 hover:bg-zinc-100 rounded text-zinc-600"><ChevronRight size={20} /></button>
              </div>
              <h2 className="text-xl font-extrabold text-zinc-900 uppercase">{currentDate.toLocaleDateString('en-US', { month: 'long', year: 'numeric' })}</h2>
            </div>

            <div className="flex gap-2">
              <Button onClick={() => setIsBlockoutModalOpen(true)} variant="outline" className="flex items-center gap-2 text-zinc-600 border-zinc-300">
                <Slash size={16} /> Block Time Off
              </Button>
              <Button onClick={() => setIsAvailModalOpen(true)} className="flex items-center gap-2">
                <Plus size={16} /> Add Weekly Availability
              </Button>
            </div>
          </div>

          <Card className="overflow-hidden border-zinc-200 bg-white shadow-lg">
            <div className="grid grid-cols-8 divide-x divide-zinc-200 border-b border-zinc-200">
              <div className="p-4 bg-zinc-50"></div>
              {weekDays.map((day, i) => (
                <div key={i} className={`p-4 text-center ${day.toDateString() === new Date().toDateString() ? 'bg-zinc-900 text-white' : 'bg-zinc-50 text-zinc-900'}`}>
                  <div className="text-xs font-bold uppercase tracking-wider opacity-70">{day.toLocaleDateString('en-US', { weekday: 'short' })}</div>
                  <div className="text-lg font-extrabold">{day.getDate()}</div>
                </div>
              ))}
            </div>
            <div className="grid grid-cols-8 divide-x divide-zinc-200">
              {/* Time Column */}
              <div className="bg-zinc-50 divide-y divide-zinc-100 border-r border-zinc-200">
                {hours.map(hour => (
                  <div key={hour} className="h-20 p-2 text-xs font-bold text-zinc-400 text-right uppercase">
                    {hour > 12 ? `${hour - 12} PM` : `${hour} AM`}
                  </div>
                ))}
              </div>

              {/* Days Columns */}
              {weekDays.map((day, dIndex) => {
                const dayOfWeek = day.getDay();
                return (
                  <div key={dIndex} className="relative bg-zinc-100 divide-y divide-zinc-200/50">
                    {hours.map(hour => {
                      const cellDate = new Date(day);
                      cellDate.setHours(hour, 0, 0, 0);
                      const dateString = day.toISOString().split('T')[0];

                      // Check Availability
                      const isAvailable = availability.some(a => {
                        if (Number(a.dayOfWeek) !== dayOfWeek) return false;
                        const startH = parseInt(a.startTime.split(':')[0]);
                        const endH = parseInt(a.endTime.split(':')[0]);
                        return hour >= startH && hour < endH;
                      });

                      // Check Specific Date Blockout
                      const blockout = blockouts.find(b => {
                        if (b.date !== dateString) return false;
                        const startH = parseInt(b.startTime.split(':')[0]);
                        const endH = parseInt(b.endTime.split(':')[0]);
                        return hour >= startH && hour < endH;
                      });

                      // Find Availability Object to attach delete handler (if not blocked)
                      const availObj = !blockout && availability.find(a => {
                        if (Number(a.dayOfWeek) !== dayOfWeek) return false;
                        const startH = parseInt(a.startTime.split(':')[0]);
                        return hour === startH;
                      });

                      // Find Blockout Object start (for delete handler)
                      const blockoutObj = blockouts.find(b => {
                        if (b.date !== dateString) return false;
                        const startH = parseInt(b.startTime.split(':')[0]);
                        return hour === startH;
                      });

                      // Find Session
                      const session = sessions.find(s => {
                        const sTime = new Date(s.startTime);
                        return sTime.getDate() === day.getDate() &&
                          sTime.getMonth() === day.getMonth() &&
                          sTime.getHours() === hour;
                      });

                      return (
                        <div key={hour} className={`h-20 relative transition-colors ${blockout ? 'bg-[repeating-linear-gradient(45deg,#fecaca,#fecaca_10px,#fee2e2_10px,#fee2e2_20px)]' : isAvailable ? 'bg-white' : 'bg-zinc-100'}`}>
                          {isAvailable && !blockout && (
                            <div className="absolute inset-0 border-b border-zinc-50"></div>
                          )}

                          {blockout && (
                            <div className="absolute inset-0 flex items-center justify-center pointer-events-none">
                              <span className="text-[10px] font-bold text-red-800 uppercase transform -rotate-12 opacity-80 border border-red-800 px-1 rounded">Blocked</span>
                            </div>
                          )}

                          {/* Delete Weekly Availability Button */}
                          {availObj && (
                            <div className="absolute top-1 right-1 z-10 opacity-0 hover:opacity-100 transition-opacity">
                              <button
                                onClick={(e) => handleDeleteAvailability(availObj.id, e)}
                                className="bg-zinc-200 text-zinc-600 rounded-full p-1 hover:bg-red-100 hover:text-red-600"
                                title="Remove recurring availability"
                              >
                                <X size={12} />
                              </button>
                            </div>
                          )}

                          {/* Delete Blockout Button */}
                          {blockoutObj && (
                            <div className="absolute top-1 right-1 z-10 opacity-100">
                              <button
                                onClick={(e) => handleDeleteBlockout(blockoutObj.id, e)}
                                className="bg-red-100 text-red-600 rounded-full p-1 hover:bg-red-200"
                                title="Remove time off"
                              >
                                <X size={12} />
                              </button>
                            </div>
                          )}

                          {session && (
                            <div
                              onClick={() => { setSelectedSessionId(session.id); setActiveTab('DASHBOARD'); }}
                              className="absolute inset-1 bg-zinc-900 text-white p-2 rounded text-xs cursor-pointer hover:bg-black shadow-md z-20 flex flex-col justify-between border-l-2 border-zinc-500"
                            >
                              <span className="font-bold line-clamp-1">{getClassName(session.classTypeId)}</span>
                              <span className="opacity-80 font-medium text-[10px]">{session.enrolledUserIds.length}/{session.capacity} Enrolled</span>
                            </div>
                          )}

                          {!isAvailable && !session && !blockout && (
                            <div className="absolute inset-0 bg-[linear-gradient(45deg,transparent_25%,rgba(0,0,0,0.03)_25%,rgba(0,0,0,0.03)_50%,transparent_50%,transparent_75%,rgba(0,0,0,0.03)_75%,rgba(0,0,0,0.03)_100%)] bg-[length:8px_8px]"></div>
                          )}
                        </div>
                      );
                    })}
                  </div>
                )
              })}
            </div>
          </Card>

          <div className="mt-4 flex flex-wrap items-center gap-6 text-xs font-bold text-zinc-500 uppercase tracking-wide justify-end">
            <div className="flex items-center gap-2">
              <div className="w-4 h-4 bg-zinc-100 border border-zinc-200 rounded"></div>
              <span>Unavailable</span>
            </div>
            <div className="flex items-center gap-2">
              <div className="w-4 h-4 bg-white border border-zinc-200 rounded"></div>
              <span>Available</span>
            </div>
            <div className="flex items-center gap-2">
              <div className="w-4 h-4 bg-red-100 border border-red-200 rounded bg-[repeating-linear-gradient(45deg,#fecaca,#fecaca_2px,#fee2e2_2px,#fee2e2_4px)]"></div>
              <span>Blocked Off</span>
            </div>
            <div className="flex items-center gap-2">
              <div className="w-4 h-4 bg-zinc-900 rounded"></div>
              <span>Scheduled Class</span>
            </div>
          </div>
        </div>
      )}

      {/* AVAILABILITY MODAL */}
      <Modal isOpen={isAvailModalOpen} onClose={() => setIsAvailModalOpen(false)} title="Set Recurring Availability">
        <form onSubmit={handleAvailSubmit} className="space-y-6">
          <p className="text-sm text-zinc-500">Define your standard weekly working hours. Sessions can only be booked during these times.</p>
          <div>
            <label className="block text-xs font-bold text-zinc-500 uppercase tracking-wider mb-2">Day of Week</label>
            <select
              value={availForm.dayOfWeek}
              onChange={(e) => setAvailForm({ ...availForm, dayOfWeek: Number(e.target.value) })}
              className="w-full px-4 py-2 border border-zinc-300 rounded-md focus:ring-zinc-900 focus:border-zinc-900 text-zinc-900 font-sans"
            >
              <option value={0}>Sunday</option>
              <option value={1}>Monday</option>
              <option value={2}>Tuesday</option>
              <option value={3}>Wednesday</option>
              <option value={4}>Thursday</option>
              <option value={5}>Friday</option>
              <option value={6}>Saturday</option>
            </select>
          </div>
          <div className="grid grid-cols-2 gap-4">
            <div>
              <label className="block text-xs font-bold text-zinc-500 uppercase tracking-wider mb-2">Start Time</label>
              <input
                type="time" required
                value={availForm.startTime}
                onChange={(e) => setAvailForm({ ...availForm, startTime: e.target.value })}
                className="w-full px-4 py-2 border border-zinc-300 rounded-md focus:ring-zinc-900 focus:border-zinc-900 text-zinc-900"
              />
            </div>
            <div>
              <label className="block text-xs font-bold text-zinc-500 uppercase tracking-wider mb-2">End Time</label>
              <input
                type="time" required
                value={availForm.endTime}
                onChange={(e) => setAvailForm({ ...availForm, endTime: e.target.value })}
                className="w-full px-4 py-2 border border-zinc-300 rounded-md focus:ring-zinc-900 focus:border-zinc-900 text-zinc-900"
              />
            </div>
          </div>
          <div className="flex gap-4 pt-4 border-t border-zinc-100">
            <Button type="button" variant="secondary" onClick={() => setIsAvailModalOpen(false)} className="flex-1 text-zinc-900">Cancel</Button>
            <Button type="submit" className="flex-1">Add Availability</Button>
          </div>
        </form>
      </Modal>

      {/* BLOCKOUT MODAL */}
      <Modal isOpen={isBlockoutModalOpen} onClose={() => setIsBlockoutModalOpen(false)} title="Block Time Off">
        <form onSubmit={handleBlockoutSubmit} className="space-y-6">
          <p className="text-sm text-zinc-500">Block out a specific date and time for appointments, vacations, or personal time.</p>
          <div>
            <label className="block text-xs font-bold text-zinc-500 uppercase tracking-wider mb-2">Date</label>
            <input
              type="date" required
              value={blockoutForm.date}
              onChange={(e) => setBlockoutForm({ ...blockoutForm, date: e.target.value })}
              className="w-full px-4 py-2 border border-zinc-300 rounded-md focus:ring-zinc-900 focus:border-zinc-900 text-zinc-900 font-sans"
            />
          </div>
          <div className="grid grid-cols-2 gap-4">
            <div>
              <label className="block text-xs font-bold text-zinc-500 uppercase tracking-wider mb-2">Start Time</label>
              <input
                type="time" required
                value={blockoutForm.startTime}
                onChange={(e) => setBlockoutForm({ ...blockoutForm, startTime: e.target.value })}
                className="w-full px-4 py-2 border border-zinc-300 rounded-md focus:ring-zinc-900 focus:border-zinc-900 text-zinc-900"
              />
            </div>
            <div>
              <label className="block text-xs font-bold text-zinc-500 uppercase tracking-wider mb-2">End Time</label>
              <input
                type="time" required
                value={blockoutForm.endTime}
                onChange={(e) => setBlockoutForm({ ...blockoutForm, endTime: e.target.value })}
                className="w-full px-4 py-2 border border-zinc-300 rounded-md focus:ring-zinc-900 focus:border-zinc-900 text-zinc-900"
              />
            </div>
          </div>
          <div>
            <label className="block text-xs font-bold text-zinc-500 uppercase tracking-wider mb-2">Reason</label>
            <input
              type="text"
              placeholder="e.g. Doctor's Appt"
              value={blockoutForm.reason}
              onChange={(e) => setBlockoutForm({ ...blockoutForm, reason: e.target.value })}
              className="w-full px-4 py-2 border border-zinc-300 rounded-md focus:ring-zinc-900 focus:border-zinc-900 text-zinc-900"
            />
          </div>
          <div className="flex gap-4 pt-4 border-t border-zinc-100">
            <Button type="button" variant="secondary" onClick={() => setIsBlockoutModalOpen(false)} className="flex-1 text-zinc-900">Cancel</Button>
            <Button type="submit" variant="danger" className="flex-1">Block Time</Button>
          </div>
        </form>
      </Modal>

    </div>
  );
};
